### ISSUE TITLE
dropped dits

### ISSUE THREAD

**Issue by worsthorse** [scp93ch/morse-pro#1]
when training at speeds greater than 25WPM, the first dit of letters like "r", "l" and "f" is obscured or cut off, so "root" becomes "noot" and "fake" is heard as "rake".  the problem is most easily heard when listening to words and is less apparent when playing letter blocks like "r r r r r". 

the problem is not apparent at 20WPM or less.  

i am guessing that inserting a short delay before playing a string will fix the problem.

thanks!
bill K7WXW

**Comment by scp93ch** [comment]
Thanks for the bug report.

Could you try listening to the same code and speed on my [Morse translator](https://morsecode.scphillips.com/translator.html)?  The tools on my website run a slightly more recent version of this library and I think I may have fixed this issue already in the unreleased code.

**Comment by worsthorse** [comment]
good morning,

i tested it this morning on both firefox (57) and chrome (64). pitch, 600. speed, 25 and 30, farnsworth, 25 and 30. 

it is improved on firefox and works fine on chrome.  on firefox, there is still some sort of glitch, though, that is distorting the first dit. it is not apparent on chrome.

hope this helps.

thanks,
bill

**Comment by scp93ch** [comment]
Thanks, that's useful. I'll make a note to at least make a configurable pause at the start.

**Comment by cniesen** [comment]
The configurable pause would be really nice.  I'm experience a dropped dit at random times using chrome and firefox on an android phone when working with the [trainer](https://morsecode.scphillips.com/trainer.html)

**Comment by scp93ch** [comment]
I've just uploaded v2.0.0 which has a configurable initial pause in the generated waveform. I believe this should solve your problem.

**Comment by scp93ch** [comment]
@cniesen are you able to check that your problem is solved? Then I can close this issue. Thanks.

**Comment by cniesen** [comment]
Sounds great on my Samsung Galaxy S6 (Android 7), a LG K20 Plus (Android 7), and Motorola Moto e5 Plus (Android 8). But dits are missing on my Galaxy S4 (Android 5.0.1). 

Video of S4 https://youtu.be/KsgqVjGXHFY

Tested always with the stock chrome browser.

**Comment by scp93ch** [comment]
Thanks for the tests.

I think that I have fixed the issue in this morse-pro library but that I need to expose the configurable start-up delay in the interface of the tools on my website. At the moment they use a hard-coded 50ms delay if I remember correctly.

I'll close this issue as the issue on morse-pro itself is fixed.

I'll add the configurable start-up delay to a private issue tracker I have for the website.
