### ISSUE TITLE
Downloaded File Names

### ISSUE THREAD

**Issue by yottalogical** [scp93ch/morse-pro#2]
It would be useful for the file names of downloaded morse audio to be what the morse means. Right now they are all `morse.wav`. This makes it impossible to manage multiple morse audio files at once.

**Comment by scp93ch** [comment]
Sorry for the slow reply. I'm not sure what code you are using to cause the filenames to be the same. I don't think that's part of the library is it?

The way I use it is something like:

```html
<a role="button" id="download" download="morse.wav">Download</a>
```

Using jQuery you can change the download property to be whatever filename you want:

```javascript
$download = $('#download');
$download.attr("href", getDataURI(RiffWave.getData(morseCWWave), RiffWave.getMIMEType()));
$download.prop("download", "filename.xyz");
```

I hope that helps?
