### ISSUE TITLE
Shortcut keys do not work as explained in help file

### ISSUE THREAD

**Issue by rpoulin** [scp93ch/morse-pro#3]
j & k target the session instead of the segment
p & n highlight the wrong key but increment/decrement ok

not a biggie because after trying out all of the different keys, I finally figured out that , . and / work

btw, thanks for this site. My donation will prove my gratitude.

**Comment by scp93ch** [comment]
Thanks Ron.

This repository is for the underlying library rather than the web pages I build on top of it. However, you are correct in reporting that I confused j/k and p/n: I'll change the documentation.

I'm not sure what you mean by "highlight the wrong key"?

**Comment by scp93ch** [comment]
Sorry, I now see: p & n AND j & k were changing the session.

I'll change it so that j & k change the segment (as currently specified in the docs).

Still not sure about "highlight the wrong key"?

**Comment by rpoulin** [comment]
Thanks.  When one presses a keyboard key, the web page lights up a control
tile like forward or reverse.  That is what I was pointing out.  Not a big
deal but I thought you would be interested.

**Comment by scp93ch** [comment]
Interesting. What browser (and version) do you see that in?

**Comment by rpoulin** [comment]
HI,

I am on Linux using Version 66.0.3359.139 (Official Build) (64-bit).  Not
your usual customer probably.

Cheers!

**Comment by rpoulin** [comment]
chrome that is...
ron

**Comment by rpoulin** [comment]
Hi again,

You know what would be nice is if the r key would restart the current
session from the beginning.  to restart the current segment from the
beginning the / key works well.  Right now, the r and the / do the same
thing except that the r starts from the beginning the / has the ability to
pause in the middle of the current segment.

Maybe a capital R sould take you to the beginning of the current session.
I find myself hitting the back key several times to get back to the
beginning of the current session.  What do you think?

Ron  (let me know if you want me to do this on git hub instead)

**Comment by scp93ch** [comment]
Sounds like a good idea. I'll get onto it next week.

**Comment by scp93ch** [comment]
Hi Ron, I've just added the "R" shortcut as you suggested.

**Comment by rpoulin** [comment]
Thank you.
Ron
