### ISSUE TITLE
procedure words not recognized as valid morse characters. 

### ISSUE THREAD

**Issue by IIAOPSW** [scp93ch/morse-pro#7]
In the morse standard there are several "non-printable characters" meant to be procedure words, often denoted by letters with an underline or overline to indicate that the inter-letter spacing should be omitted. The most famous example of this being the distress signal _SOS_ (which in some books is actually written as _VZE_). Contrary to popular belief, "... --- ..." is NOT a correct distress signal (it is the letters "SOS"). The correct distress signal is "...---..." (no spaces).  

https://en.wikipedia.org/wiki/Prosigns_for_Morse_code

On the prosigns I have tested, your morse translator erroneously states "This is not valid Morse code, but it can be played anyway." and incorrectly outputs "#".

**Comment by IIAOPSW** [comment]
Should have specified, this error was on the web site version, for which I'm assuming this code is the back end.

**Comment by scp93ch** [comment]
Hi,
The library does support prosigns. The page you tried is for general users who may be confused by prosigns so they are not enabled. There is an alternative page in the "training" section which you should find works fine: https://morsecode.world/international/trainer/generator.html

Insert prosigns as e.g. `<SOS>`

If you want the latest library code, it is now on github: https://gitlab.com/scphillips/morse-pro

**Comment by IIAOPSW** [comment]
Fair enough. I'm going to close the issue with a final remark that it would be better if the lack of prosigns (or any other subtle complexities) were disclaimed somewhere on the page and/or if there was a checkbox option to enable them anyway.
